=== nathanryan/answerquestxml/AnswerQuest/build/web/WEB-INF/QuestionsSchema.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="questionlist">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="topic" maxOccurs="unbounded" minOccurs="0">
          <xs:annotation>
            <xs:documentation>Each Topic creates a new Topics and Questions Page</xs:documentation>
          </xs:annotation>
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="topicname"/>
              <xs:element type="xs:string" name="topicinfo"/>
              <xs:element type="xs:string" name="topicimage"/>
              <xs:element name="questionmembers">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="question" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:string" name="name"/>
                          <xs:element type="xs:string" name="questiontext"/>
                          <xs:element type="xs:string" name="correct"/>
                          <xs:element type="xs:string" name="incorrect"/>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="optional"/>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="id" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== nathanryan/answerquestxml/AnswerQuest/web/WEB-INF/Questions.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="Topics.xsl" type="text/xsl"?>
<?xml-stylesheet href="QuestionMember.xsl" type="text/xsl"?>
<?xml-stylesheet href="AdminQuestionMember.xsl" type="text/xsl"?>
<!-- BSHC2A Team OBCT Nathan Ryan x13448212 Keith Lok x13323161 Jefferson Tolentino x13452702 Daniel Benhamou x13341086 Usman Akhtar x13358421 -->
<!--/**
 *
 * @author Daniel Benhamou, x13341086 
 * @author Nathan Ryan, x13448212 
 */ -->
<questionlist xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:noNamespaceSchemaLocation='QuestionsSchema.xsd'>

<!--Each Topic creates a new Topics and Questions Page -->
    <topic id ="t1">

        <topicname>Topic One</topicname>
        <topicinfo> This topic is all about Geography ! </topicinfo>
        <topicimage>img/geog.png</topicimage> 
	
        <questionmembers>
	
            <question id="a1">
                
                <name>Question A One</name>
                                
                <questiontext>What is the capital of Spain  ? </questiontext>
			                                                                                       
                <correct> Madrid  </correct>
                                
                <incorrect> Valencia </incorrect>

            </question>
			
			
			
            <question id="a2">
                            
                <name>Question A Two</name>
                                
                <questiontext>Which country has the largest population in the World ? </questiontext>                       
                                                                                              
                <correct> China  </correct>
                                
                <incorrect> U.S.A </incorrect>
	
            </question>
			
            <question id="a3">
                
                <name>Question A Three</name>
                                
                <questiontext>On which continent are the Himalayas located ? </questiontext>
                                                               
                <correct> Asia  </correct>
                                
                <incorrect> South America </incorrect>
	
            </question>
			
            <question id="a4">
                            
                <name>Question A Four</name>
                                
                <questiontext>On which continent is Ghana located ? </questiontext>
                                                               
                <correct> Africa  </correct>
                                
                <incorrect> Europe </incorrect>
	
            </question>
                        
            <question id="a5">
                            
                <name>Question A Five</name>
                                
                <questiontext>What type of stone is found in The Burren in County Clare ? </questiontext>
                                                               
                <correct> Limestone  </correct>
                                
                <incorrect> Basalt </incorrect>
	
            </question>
            
            <question id="a6">
                            
                <name>Question A Six</name>
                                
                <questiontext>You have reached the end of this Topic. Click next if you would like to go to the next Topic. </questiontext>
                                                               
                <correct></correct>
                                
                <incorrect></incorrect>
	
            </question>

        </questionmembers>
	
    </topic>
        
    <topic id ="t2">

        <topicname>Topic Two</topicname>
        <topicinfo> This topic is all about History ! </topicinfo> 
        <topicimage>img/history.gif</topicimage>
	
        <questionmembers>
	
            <question id="b1">
                
                <name>Question B One</name>
                                
                <questiontext>Who was Prime Minister of the U.K during World War 2 ? </questiontext>
			                                                                                       
                <correct> Winston Churchill  </correct>
                                
                <incorrect> Tony Blair </incorrect>

            </question>
			
			
			
            <question id="b2">
                            
                <name>Question B Two</name>
                                
                <questiontext>What year did World War 1 begin ? </questiontext>                       
                                                                                              
                <correct> 1914  </correct>
                                
                <incorrect> 1920 </incorrect>
	
            </question>
			
            <question id="b3">
                
                <name>Question B Three</name>
                                
                <questiontext>What century did the Vikings first come to Ireland ? </questiontext>
                                                               
                <correct> 8th Century  </correct>
                                
                <incorrect> 10th Century </incorrect>
	
            </question>
			
            <question id="b4">
                            
                <name>Question B Four</name>
                                
                <questiontext>In what year did The Great Famine begin ? </questiontext>
                                                               
                <correct> 1845  </correct>
                                
                <incorrect> 1700 </incorrect>
	
            </question>
            
            <question id="b5">
                            
                <name>Question B Five</name>
                                
                <questiontext>What is the name of the founder of the Mongol Empire ? </questiontext>
                                                               
                <correct>Genghis Khan </correct>
                                
                <incorrect> Kublai Khan </incorrect>
	
            </question>
            
            <question id="b6">
                            
                <name>Question B Six</name>
                                
                <questiontext>You have reached the end of this Topic. Click next if you would like to go to the next Topic. </questiontext>
                                                               
                <correct></correct>
                                
                <incorrect></incorrect>
	
            </question>

        </questionmembers>
	
    </topic>
    
    <topic id ="t3">

        <topicname>The Irish Language</topicname>
        <topicinfo> This is all about Irish ! </topicinfo> 
        <topicimage>img/ireland.jpg</topicimage>
	
        <questionmembers>
	
            <question id="c1">
                
                <name>Question C One</name>
                                
                <questiontext> How do you say 'Hello' ? </questiontext>
			                                                                                       
                <correct> Dia duit </correct>
                                
                <incorrect> Conas ata tu </incorrect>

            </question>
			
			
			
            <question id="c2">
                            
                <name>Question C Two</name>
                                
                <questiontext> How do you say 'What is your name' ? </questiontext>                       
                                                                                              
                <correct>  Cén t-ainm atá ort? </correct>
                                
                <incorrect> Caca Milis </incorrect>
	
            </question>
			
            <question id="c3">
                
                <name>Question C Three</name>
                                
                <questiontext> What is the Irish word for Chapel ? </questiontext>
                                                               
                <correct> Séipéal  </correct>
                                
                <incorrect> Caisléan </incorrect>
	
            </question>
			
            <question id="c4">
                            
                <name>Question C Four</name>
                                
                <questiontext> What is the Irish word for Church ? </questiontext>
                                                               
                <correct>  Teach an Phobail </correct>
                                
                <incorrect> Bothar  </incorrect>
	
            </question>
            
            <question id="c5">
                            
                <name>Question C Five</name>
                                
                <questiontext> What is the Irish word for Parents ?</questiontext>
                                                               
                <correct> Thuismitheoirí  </correct>
                                
                <incorrect> Deirfiúr </incorrect>
	
            </question>
            
            <question id="c6">
                            
                <name>Question C Six</name>
                                
                <questiontext>You have reached the end of this Topic. Click next if you would like to go to the next Topic. </questiontext>
                                                               
                <correct></correct>
                                
                <incorrect></incorrect>
	
            </question>
        </questionmembers>
	
    </topic>
    
    <topic id ="t4">

        <topicname>Topic Four</topicname>
